
// Assignment Code
var generateBtn = document.querySelector("#generate");

// Define variable. From Sandesh - TA (Slack)
let lowerCase = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",];
let upperCase = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z",];
let numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
let specialCharacters = ['@','%','+','\\','/',"'",'!','#','$','^','?',':',',',')','(','}','{',']','[','~','-','_','.'];


// Define generatePassword() & Test Button
function generatePassword() {
  console.log("you have clicked the button")

//  1. Prompt the user for the password criteria
//    a. Password length 8 < 128 charactes
      characterLength = prompt ('Password length between 8 and 128 charactes');

//      ensure the character length  between 8 - 128 and ensure once character length is selected
        if (characterLength >=8 && characterLength <= 128) {
        } else {
          prompt ('Password must be between 8 and 128 characters');
        }
//    b. Lowercase, 
      confirmLowercase = confirm ('Would you like to have LOWERCASE?');

        function getRandomInt () {
          let rand = getRandomInt(lowerCase.length);
          console.log("Lower Case Password")
        }
//    c. Uppercase
      confirmUppercase = confirm ('Would you like to have UPPERCASE?');
//    d. Numbers
      confirmNumbers = confirm ('Would you like to have NUMBERS?');
//    e. Special characters
      confirmSpecialCharacters = confirm ('Would you like to have SPECIAL CHARACTERS?');
//
//  2. Validate the input.


//  3. Generate password based on criteria.
//    

//  4. Display password to the page . will return "password generated"
  return "Password generated by Ch1";
}

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);


